### ISSUE TITLE
Example for non fixed constraints

### ISSUE THREAD

**Issue by ArnaudDeza** [leggedrobotics/rayen#1]
Hi,

I am interested in your work and I was wondering if you could point me to an example where Rayen is used for a constraint of the neural network that is based on the input to the network, I.e non fixed constraints

I want to use your method to ensure a constraint Ax<=b is met, however, the A matrix depends on the input to the neural network whereas b is fixed.

Thanks,
Arnaud

**Comment by jtorde** [comment]
Hi @ArnaudDeza,

Thanks for your question. Right now, and as described in the paper, RAYEN's code is designed for fixed constraints. We are however working on an extension that will allow RAYEN to handle non-fixed constraints. Have a look at Section VI-B ("Non-fixed Constraints") of the paper for a detailed description of several ways to do this. The code will be released open source once it is finished. 

And, as always, we also welcome pull requests with new features. 

Hope this helps
